name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Build the image with both the commit SHA and 'latest' tag
          docker build -t ghcr.io/thebiemgamer/youtubedl:${{ github.sha }} \
                       -t ghcr.io/thebiemgamer/youtubedl:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/thebiemgamer/youtubedl:${{ github.sha }}
          docker push ghcr.io/thebiemgamer/youtubedl:latest
